"""add administrator_sessions table

Revision ID: 496829188b3f
Revises: 7cd8452607fd
Create Date: 2026-08-03 04:34:18.564467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496829188b3f'
down_revision: Union[str, None] = '7cd8452607fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator_sessions',
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['administrators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('administrator_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_administrator_sessions_admin_id', ['admin_id'], unique=False)
        batch_op.create_index('ix_administrator_sessions_expires_at', ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_administrator_sessions_expires_at')
        batch_op.drop_index('ix_administrator_sessions_admin_id')

    op.drop_table('administrator_sessions')
    # ### end Alembic commands ###
