"""create initial schema

Revision ID: 7cd8452607fd
Revises: 
Create Date: 2026-08-02 21:58:31.392539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd8452607fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clients',
    sa.Column('agent_guid', sa.Uuid(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('operating_system', sa.String(length=100), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'UNKNOWN', name='client_status', native_enum=False), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_guid'),
    sa.UniqueConstraint('api_key_hash')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('ix_clients_hostname', ['hostname'], unique=False)
        batch_op.create_index('ix_clients_status', ['status'], unique=False)

    op.create_table('repository_packages',
    sa.Column('software_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('installer_filename', sa.String(length=255), nullable=False),
    sa.Column('installer_type', sa.Enum('EXE', 'MSI', name='installer_type', native_enum=False), nullable=False),
    sa.Column('silent_command', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.Enum('APPROVED', 'INACTIVE', name='approval_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_packages_software_name'), ['software_name'], unique=False)

    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', name='audit_severity', native_enum=False), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['administrators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_audit_logs_timestamp', ['timestamp'], unique=False)

    op.create_table('deployments',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_admin_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['administrators.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository_packages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_repository_id'), ['repository_id'], unique=False)

    op.create_table('software_inventory',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('software_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('install_location', sa.String(length=500), nullable=True),
    sa.Column('last_scanned', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('software_inventory', schema=None) as batch_op:
        batch_op.create_index('ix_software_inventory_client_software', ['client_id', 'software_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_software_inventory_software_name'), ['software_name'], unique=False)

    op.create_table('deployment_targets',
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'INSTALLING', 'COMPLETED', 'FAILED', 'CANCELLED', name='deployment_status', native_enum=False), nullable=False),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id', 'client_id', name='uq_deployment_target_deployment_client')
    )
    with op.batch_alter_table('deployment_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_targets_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_deployment_targets_client_status', ['client_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_targets_deployment_id'), ['deployment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_targets_deployment_id'))
        batch_op.drop_index('ix_deployment_targets_client_status')
        batch_op.drop_index(batch_op.f('ix_deployment_targets_client_id'))

    op.drop_table('deployment_targets')
    with op.batch_alter_table('software_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_software_inventory_software_name'))
        batch_op.drop_index('ix_software_inventory_client_software')

    op.drop_table('software_inventory')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_repository_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_created_by_admin_id'))

    op.drop_table('deployments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_timestamp')
        batch_op.drop_index('ix_audit_logs_event_type')

    op.drop_table('audit_logs')
    with op.batch_alter_table('repository_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_packages_software_name'))

    op.drop_table('repository_packages')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('ix_clients_status')
        batch_op.drop_index('ix_clients_hostname')

    op.drop_table('clients')
    op.drop_table('administrators')
    # ### end Alembic commands ###
