"""add system_configuration table

Revision ID: a1c3f9d2e6b7
Revises: 96d9bed20171
Create Date: 2026-08-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c3f9d2e6b7'
down_revision: Union[str, None] = '96d9bed20171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'system_configuration',
        sa.Column('session_inactivity_timeout_minutes', sa.Integer(), nullable=False),
        sa.Column('client_heartbeat_timeout_minutes', sa.Integer(), nullable=False),
        sa.Column('max_installer_upload_size_mb', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_configuration')
    # ### end Alembic commands ###
