"""add publisher to repository_packages

Revision ID: f3a7c1d92b44
Revises: 18c18ba88820
Create Date: 2026-08-16 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a7c1d92b44'
down_revision: Union[str, None] = '18c18ba88820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_packages', schema=None) as batch_op:
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
