"""
Client Management dashboard response schemas (DTOs).

Introduced by DASH-004 (Backlog "Client Management Dashboard" - "Client
List", "Client Detail", "Client Software / Inventory"), per the DTO
Pattern (SAD Section 5.8). These are response-only shapes - none of the
three DASH-004 pages accept a request body beyond the existing
administrator session cookie and query-string filters - consumed both by
the JSON API (``GET /api/admin/dashboard/clients...``) and by the
server-rendered templates (``GET /dashboard/clients...``), which are
populated from the same ``DashboardService`` calls rather than a second,
duplicated data path (the same pattern already established by
DASH-001/DASH-002/DASH-003).

No new database table, column, or migration is introduced - every field
below is derived entirely from existing columns already exposed by
``Client``, ``SoftwareInventory``, and the results of
``VersionComparisonService.compare_client_inventory`` (FR-007), plus the
already-existing ``DeploymentTargetDetail`` (DASH-002) for a client's
deployment history.
"""

from __future__ import annotations

import uuid
from datetime import date as date_type
from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field

from backend.models.enums import ClientStatus, UpdateStatus
from backend.schemas.deployment_monitor import DeploymentTargetDetail
from backend.schemas.updates import ClientUpdateStatusSummary


class ClientListItem(BaseModel):
    """
    A single registered client, as shown on the Client List page
    (DASH-004).

    ``status`` is the *effective*, read-time status computed by
    ``DashboardService._effective_client_status`` (the same helper
    DASH-001's Client Summary card already uses) - never read directly
    from the stored ``Client.status`` column. See that method's docstring
    for the full design rationale.
    """

    id: uuid.UUID = Field(description="Primary key of the Client row.")
    hostname: str = Field(description="Client hostname (FR-001).")
    logged_in_user: Optional[str] = Field(
        default=None,
        description="Currently logged-in Windows user on the client.",
    )
    ip_address: str = Field(description="Client's last-known IP address (FR-001).")
    operating_system: str = Field(description="Client operating system (FR-001).")
    agent_version: str = Field(description="Installed CPMS Client Agent version (FR-001).")
    status: ClientStatus = Field(description="Effective, read-time status: Online, Offline, or Unknown (FR-014).")
    last_heartbeat: Optional[datetime] = Field(
        default=None, description="Most recent heartbeat timestamp, if the client has ever sent one (FR-003)."
    )
    registration_date: datetime = Field(description="When the client first registered (FR-001).")


class ClientListResponse(BaseModel):
    """Complete payload for the Client List page/API: every matching client, after any filters."""

    clients: List[ClientListItem] = Field(default_factory=list)
    total: int = Field(ge=0, description="Number of clients matching the current filters.")


class ClientDetailResponse(BaseModel):
    """
    Complete payload for the Client Detail page/API: a single client's
    identifying/status information plus its recent deployment history.

    ``deployment_targets`` reuses ``DeploymentTargetDetail`` (DASH-002)
    unmodified, populated via ``DeploymentRepository.list_target_details``
    filtered by this client's id - no deployment query logic is
    duplicated here.
    """

    id: uuid.UUID = Field(description="Primary key of the Client row.")
    agent_guid: uuid.UUID = Field(description="Persistent Agent GUID generated by the Client Agent (FR-001).")
    hostname: str
    logged_in_user: Optional[str] = Field(
    default=None,
    description="Currently logged-in Windows user on the client.",
    )
    ip_address: str
    operating_system: str
    agent_version: str
    status: ClientStatus = Field(description="Effective, read-time status: Online, Offline, or Unknown (FR-014).")
    last_heartbeat: Optional[datetime] = None
    registration_date: datetime
    deployment_targets: List[DeploymentTargetDetail] = Field(
        default_factory=list,
        description="This client's most-recent deployment targets (reused from DASH-002).",
    )


class ClientSoftwareItem(BaseModel):
    """
    One installed software item for a client, combining
    ``VersionComparisonService.compare_client_inventory``'s FR-007
    comparison outcome with ``install_date`` from the underlying
    ``SoftwareInventory`` record (the comparison service itself has no
    reason to expose ``install_date`` - see
    ``DashboardService.get_client_software`` for how the two are merged
    by ``inventory_id`` without modifying
    ``backend.services.version_comparison_service``).
    """

    inventory_id: uuid.UUID = Field(description="Identifier of the underlying SoftwareInventory record.")
    software_name: str = Field(description="Installed application name, as reported by the client.")
    installed_version: str = Field(description="Installed application version, as reported by the client.")
    publisher: Optional[str] = Field(default=None, description="Software publisher, if reported.")
    install_date: Optional[date_type] = Field(default=None, description="Installation date, if reported.")
    status: UpdateStatus = Field(description="Up-to-Date, Update Available, or Not Managed (FR-007).")
    approved_version: Optional[str] = Field(
        default=None, description="Matched approved repository version, if a match was found."
    )
    repository_package_id: Optional[uuid.UUID] = Field(
        default=None, description="Identifier of the matched RepositoryPackage, if a match was found."
    )


class ClientSoftwareResponse(BaseModel):
    """
    Complete payload for the Client Software page/API: a client's
    installed software (after any name/publisher filters), plus the
    unfiltered FR-007 summary counts (mirroring DASH-002's convention
    that the summary always reflects the whole set, unaffected by the
    detail list's filters).
    """

    client_id: uuid.UUID = Field(description="Primary key of the Client row.")
    client_hostname: str = Field(description="Client hostname, for display.")
    items: List[ClientSoftwareItem] = Field(default_factory=list)
    summary: ClientUpdateStatusSummary = Field(
        description="Unfiltered Up-to-Date/Update Available/Not Managed counts across all installed software."
    )
