"""
Heartbeat request schema (DTO).

Per the DTO Pattern (SAD Section 5.8), this Pydantic model defines and
validates the request body for ``POST /api/agent/heartbeat`` (FR-003
Client Heartbeat).

--------------------------------------------------------------------------
DESIGN NOTE - why this schema has no required fields

FR-003's Inputs table (PRS Section 4.2) lists "Client ID", "API Key", and
"Timestamp" as heartbeat inputs. The first two are already supplied via
the ``Authorization: Bearer`` header and resolved by ``require_client_api_key``
(AUTH-002) before this schema is ever parsed - repeating them in the body
would be redundant and would let a client claim a different identity than
the one its API key actually authenticates as. The third, "Timestamp", is
generated by the *server* per FR-003's own functional behavior ("The
server records the current timestamp as the client's last heartbeat" -
PRS FR-003 step 3), not read from client-supplied data; trusting a
client-reported clock would allow a client to falsify how recently it was
actually seen and would introduce clock-skew handling this prototype does
not need.

PRS Appendix B's endpoint summary table lists ``/api/heartbeat`` without a
"Detailed Endpoint Specifications" entry (that level of detail is only
provided for the FR-019/020/021 administrator endpoints added in v1.2).
Absent a documented payload, this schema follows the same "trigger
request" shape already established for other authenticated actions with
no caller-supplied data in this codebase (``POST /api/admin/keys``,
``POST /api/deployments/{id}/cancel`` - PRS Appendix B: "No request body
fields are required; the request is a trigger.").

The schema is declared explicitly (rather than omitting a body parameter
entirely, as ``GET /api/agent/ping`` does) so that a malformed body - e.g.
a JSON array instead of an object - is rejected with a standard 422
validation error rather than silently ignored, satisfying CLIENT-002's
"validate the request payload" step. ``extra="ignore"`` (Pydantic's
default) keeps the endpoint forward-compatible: a future agent sending
additional diagnostic fields will not break against today's server.
"""

from __future__ import annotations

from pydantic import BaseModel


class HeartbeatRequest(BaseModel):
    """
    Request body for ``POST /api/agent/heartbeat`` (FR-003).

    Intentionally empty - see the module docstring for why no fields are
    required. Kept as a distinct model (rather than accepting no body at
    all) so the request is still subject to standard JSON/body validation.
    """